### ISSUE TITLE
Dependency version

### ISSUE THREAD

**Issue by hyemmie** [0xPolygonHermez/zkevm-prover#145]
I'm trying to run prover locally, but failed to install `grpc-proto` at Ubuntu 20.04
![Screen Shot 2022-10-17 at 10 11 31 PM](https://user-images.githubusercontent.com/44224497/196952691-e9fe9791-2b7f-4969-bc5b-232c420c7bb0.png)

so I'm trying to build binary from grpc github (https://github.com/grpc/grpc) and copy it to zkevm-prover/src/grpc folder. I need to know exact version of grpc to build.

Can you let me know which version of `grpc-proto` is being used?
thanks!

**Comment by hyemmie** [comment]
it was Ubuntu version problem
I'll close this issue

**Comment by wgr523** [comment]
> it was Ubuntu version problem I'll close this issue

What version will solve the problem? Ubuntu 22.04?

**Comment by hyemmie** [comment]
> > it was Ubuntu version problem I'll close this issue
> 
> 
> 
> What version will solve the problem? Ubuntu 22.04?

Yes 22.04
