### ISSUE TITLE
Rename StateDB classes to better match reality

### ISSUE THREAD

**Issue by fractasy** [0xPolygonHermez/zkevm-prover#26]

**Comment by agnusmor** [comment]
The following statedb classes have been renamed:

StateDBClient -> StateDBInterface
StateDBLocalClient -> StateDB
StateDBRemoteCliente -> StateDBRemote

Also the StateDBService have been changed to use an instance of the StateDB class to perform the set/get operations (instead to use directly the smt and database classes)
