### ISSUE TITLE
Building project

### ISSUE THREAD

**Issue by 20urc3** [0xPolygonHermez/zkevm-prover#485]
Hi,
Thanks for this interesting project.
I find myself struggling with some issue.
Firstly we can't "git clone git@github.com:0xPolygonHermez/zkevm-prover.git" it results in 
```bash
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```
Any feedback?

**Comment by josojo** [comment]
This is due to your git config. It has nothing to do with the project. try cloning with https link, if you have not setup ssh properly
