### ISSUE TITLE
Return new invalid parameters errors in processBatch() instead of cancelling the request

### ISSUE THREAD

**Issue by fractasy** [0xPolygonHermez/zkevm-prover#566]
- [x] Modify executor.proto to add new executor errors for invalid input parameters
- [x] Create PR in protocol repo with the new executor.proto
- [x] Modify executor service to returns these new errors instead of cancelling the request

**Comment by fractasy** [comment]
Implemented in v2.2.3.  Waiting for the node ( @ToniRamirezM  ) to integrate with the Sequencer and Synchronizer

**Comment by eduadiez** [comment]
Is this already included in any of the RC versions of the node? @ToniRamirezM
